### ISSUE TITLE
How to tell when document is indexed

### ISSUE THREAD

**Issue by powmedia** [rgrove/node-elastical#24]
When the callback from elasticalClient.index() runs, it seems the document has been submitted but not actually indexed yet.  This makes running unit tests slightly difficult as we have to insert a setTimeout wait of about a second before running the test.

Is there a method for submitting a callback function that runs once the document is indexed and ready to be searched?

**Comment by rgrove** [comment]
Setting the `refresh` option to `true` should cause ElasticSearch to index the document immediately, but beyond that I don't think there's anything we can do.
