### ISSUE TITLE
Compatibility for node v0.8.x?

### ISSUE THREAD

**Issue by jwyuan** [rgrove/node-elastical#25]
Right now elastical doesn't work with the latest version of node.js, due to:

"node >=0.4.0 <0.7.0" in packages.json.

Can this line be changed so that it supports node versino 0.8.x?

**Comment by rgrove** [comment]
Fixed by https://github.com/rgrove/node-elastical/pull/26

**Comment by jwyuan** [comment]
Can you update the npm registry with 0.0.9?  Currently it's still 0.0.8.  Thanks.

**Comment by rgrove** [comment]
`npm install https://github.com/rgrove/node-elastical/tarball/master`
