### ISSUE TITLE
DELETE method on requests over SSL

### ISSUE THREAD

**Issue by mehtryx** [rgrove/node-elastical#7]
Everything is great with the Auth and SSL...except...

I take fault in this one, none of the test cases run against a server with SSL connection, thats not something you can reliably have in the test cases without a public elasticsearch server you can hit over ssl or a lot more setup locally....sigh. 

Essentially however I've discovered a single fault and it is not in the code...it is in the package.json, and the fault is only in that the request library v2.1.1 had an issue when sending DELETE method over ssl, you will get an error 411 Length Required because the request is missing the Content-Length header.

So everything inside elastical works great over ssl, except any request sending the DELETE method, meaning we would need it to be increased.  I've tested locally by changing the dependency to "request": "~2.2.0" which installs 2.2.5 and all test cases pass.

I could submit this via a pull request but wanted to see if you had any particular needs for request at 2.1.x

Thanks

**Comment by rgrove** [comment]
Thanks. I've bumped the request dependency to 2.2.0 and published 0.0.5 to npm.
